### PR TITLE
Add first testing scripts for Gingerbread fork

### PR DESCRIPTION
**Pull request by karlb**
## What is tested?

Only the state after the hard fork is tested.

Currenntly tested CIPs:
* Gaslimit: A contract using the GASLIMIT opcode is deployed and its result is compared against the value returned from the JSON-RPC
* Constant header fields: The values of the header fields are checked in the JSON-RPC response

## Notes

I used `forge` to deploy the gaslimit test contract and `cast` (both tools are part of Foundry) to interact with it and the RPC. Usually forge integrates with git, but this integration caused problems in the existing repo, so I want without the git integration for now.

Shell scripts check the return values. This might not be the best choice, but it works fine for the existing test and allows easily integrating arbitrary tooling for the tests if necessary. If this choice turns out to be bad when testing more CIPs, we can still change it.

## Related issues

* Closes https://github.com/celo-org/celo-blockchain-planning/issues/68
* Closes https://github.com/celo-org/celo-blockchain-planning/issues/69
* Part of https://github.com/celo-org/celo-blockchain-planning/issues/71

### CODE REVIEW

**Comment by palango** [comment]
I just ran this locally on current `master` and the gaslimit test passed, where it shouldn't.

```
% ./run_all_tests.sh

Run test_constant_header_fields.sh
FAIL test_constant_header_fields.sh ❌

Run test_gas_limit.sh
Gas limits: 13000000 (opcode) 13000000 (block)
PASS test_gas_limit.sh
```

**Comment by karlb** [comment]
> I just ran this locally on current `master` and the gaslimit test passed, where it shouldn't.
> 
> ```
> % ./run_all_tests.sh
> 
> Run test_constant_header_fields.sh
> FAIL test_constant_header_fields.sh ❌
> 
> Run test_gas_limit.sh
> Gas limits: 13000000 (opcode) 13000000 (block)
> PASS test_gas_limit.sh
> ```

Why shouldn't it? The [gaslimit PR](https://github.com/celo-org/celo-blockchain/pull/2062) has been merged to master last week. I'm more suprised that the test_constant_header_fields test fails, since that should succeed on master, too.

It looks like it works for all blocks but genesis. I assume that is because the genesis block does not pass through `prepareBlock`. I'll check.

**Comment by palango** [comment]
> Why shouldn't it? The [gaslimit PR](https://github.com/celo-org/celo-blockchain/pull/2062) has been merged to master last week. I'm more suprised that the test_constant_header_fields test fails, since that should succeed on master, too.

Ah, I missed that that one was merged already. :) Then it makes sense.

**Comment by karlb** [comment]
> I'm more suprised that the test_constant_header_fields test fails, since that should succeed on master, too.
> 
> It looks like it works for all blocks but genesis. I assume that is because the genesis block does not pass through `prepareBlock`. I'll check.

With https://github.com/celo-org/celo-blockchain/pull/2130/commits/eb171b41bd4cdb6363522082647699a5ee3dabf8, the tests will now pass even at block zero.

**Review by palango — APPROVED** [review]
Just checked again, now all tests pass even on genesis block. Looks good, thanks!

**Pull request merged**
